### ISSUE TITLE
New features to add for V2

### ISSUE THREAD

**Issue by kichinsky** [kichinsky/CanvasTools-for-VOTT#2]
Based on issues for the VoTT (in priority order)
- [x] Implement the basic Toolbar UI element for choosing selection mode.
- [ ] [Lasso/polygon selection](https://github.com/Microsoft/VoTT/issues/243). 1) New selection and manipulation modes. 2) Various options to implement the tool UI are possible. 3) UI to choose selection mode (visual + shortcuts), 4) Changes to the sorting model..
- [ ] [One point selection mode](https://github.com/Microsoft/VoTT/issues/303). 1) UI to selection mode, 2) Changes to the storing model.
- [ ] [Photo adjustments](https://github.com/Microsoft/VoTT/issues/242). 1) UI to select photo filters and manage pipeline (visual + shortcuts?). 2) New filters.
- [x] [Template boxes](https://github.com/Microsoft/VoTT/issues/245). One-click boxes or points creation.
- [ ] New coloring schemas. Generate inclusive pallets sets, taking into account contrast ratio with the image.
- [ ] [Zoom in/out ](https://github.com/Microsoft/VoTT/issues/247). 1) Scaling engine for both the underlaying image (in canvas element) and the collection of regions. 2) UI for scaling (visual + shortcuts)
- [ ] Implement an advanced version of Toolbar allowing edigitng, pipelines, etc.

**Comment by kichinsky** [comment]
Split requests in separate issues or better tracking. Closing the issue.
